apiVersion: v1
clusters:
- cluster:
    server: https://rancher.fabrique.social.gouv.fr/k8s/clusters/c-m-97jxtvnv
  name: ovh-dev
contexts:
- context:
    cluster: ovh-dev
    user: ovh-dev
  name: ovh
current-context: ovh
kind: Config
preferences: {}
users:
- name: ovh-dev
  user:
    token: kubeconfig-u-z8c2x2lmlx:svtcxmp9z2fqxnxnb6c78944htkz6gpjxx59bbwmcd4w2p9jj26vj8
