[tool.poetry]
name = "amendements-intelligents"
version = "0.1.0"
description = ""
authors = ["Victor DEGLIAME <victor.degliame@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pandas = "^2.2.2"
openpyxl = "^3.1.4"
ollama = "^0.2.1"
torch = "^2.3.1"
transformers = "^4.42.1"
datasets = "^2.20.0"
accelerate = "^0.31.0"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
