app:
  annotations:
    oblik.socialgouv.io/min-limit-cpu: 2

api:
  annotations:
    oblik.socialgouv.io/min-limit-cpu: "3"
    oblik.socialgouv.io/min-request-cpu: "1"
    oblik.socialgouv.io/min-request-memory: "3Gi"
  envFrom:
    - configMapRef:
        name: graal
    - secretRef:
        name: graal-dev-app-access-key
  env:
    - name: FRONTEND_URL
      value: "https://{{ .Values.global.host }}"
    - name: PROCONNECT_REDIRECT_URI
      value: "https://api-{{ .Values.global.host }}/api/v1/auth/callback"
    - name: S3_BUCKET_NAME
      valueFrom:
        secretKeyRef:
          name: graal-dev-app-access-key
          key: bucket_name
    - name: S3_ENDPOINT
      valueFrom:
        secretKeyRef:
          name: graal-dev-app-access-key
          key: bucket_endpoint
    - name: S3_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: graal-dev-app-access-key
          key: bucket_access_key
    - name: S3_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: graal-dev-app-access-key
          key: bucket_secret_key
    - name: S3_REGION
      valueFrom:
        secretKeyRef:
          name: graal-dev-app-access-key
          key: bucket_region
    - name: USE_S3_CONFIG
      value: "true"

    - name: S3_BUCKET_ENDPOINT
      valueFrom:
        secretKeyRef:
          name: graal-dev-app-access-key
          key: bucket_endpoint
    - name: S3_BUCKET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: graal-dev-app-access-key
          key: bucket_access_key
    - name: S3_BUCKET_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: graal-dev-app-access-key
          key: bucket_secret_key
