app:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 300m
      memory: 256Mi

api:
  resources:
    requests:
      cpu: "1"
      memory: 2Gi
    limits:
      cpu: "3"
      memory: 4Gi
  envFrom:
    - configMapRef:
        name: graal
    - secretRef:
        name: graal-prod-app-access-key
    - secretRef:
        name: graal-prod
    - secretRef:
        name: pg-app
  env:
    - name: FRONTEND_URL
      value: "https://{{ .Values.global.host }}"
    - name: PROCONNECT_REDIRECT_URI
      value: "https://api-{{ .Values.global.host }}/api/v1/auth/callback"
    - name: S3_BUCKET_NAME
      valueFrom:
        secretKeyRef:
          name: graal-prod-app-access-key
          key: bucket_name
    - name: USE_S3_CONFIG
      value: "true"
    - name: S3_BUCKET_ENDPOINT
      valueFrom:
        secretKeyRef:
          name: graal-prod-app-access-key
          key: bucket_endpoint
    - name: S3_BUCKET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: graal-prod-app-access-key
          key: bucket_access_key
    - name: S3_BUCKET_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: graal-prod-app-access-key
          key: bucket_secret_key


pg:
  ~chart: pg
  cnpg-cluster:
    resources:
      requests:
        memory: 1Gi
      limits:
        cpu: "1"
        memory: 1Gi
    recovery:
      enabled: false
      ~tpl~database: "{{ .Values.global.pgDatabase }}"
      ~tpl~owner: "{{ .Values.global.pgUser }}"
      secretName: "pg-db"
      barmanObjectStore:
        ~tpl~destinationPath: "s3://graal-prod-backups/graal"
        s3Credentials:
          accessKeyId:
            ~tpl~name: "graal-prod-backups-access-key"
            key: bucket_access_key
          secretAccessKey:
            ~tpl~name: "graal-prod-backups-access-key"
            key: bucket_secret_key
          region:
            ~tpl~name: "graal-prod-backups-access-key"
            key: bucket_region
  backup:
    name: prod-ovh # backup on a new folder
