app:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 300m
      memory: 256Mi

api:
  resources:
    requests:
      cpu: "1"
      memory: 2Gi
    limits:
      cpu: "3"
      memory: 4Gi
  envFrom:
    - configMapRef:
        name: graal
    - secretRef:
        name: graal-prod-app-access-key
  env:
    - name: FRONTEND_URL
      value: "https://{{ .Values.global.host }}"
    - name: S3_BUCKET_NAME
      valueFrom:
        secretKeyRef:
          name: graal-prod-app-access-key
          key: bucket_name
    - name: S3_ENDPOINT
      valueFrom:
        secretKeyRef:
          name: graal-prod-app-access-key
          key: bucket_endpoint
    - name: S3_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: graal-prod-app-access-key
          key: bucket_access_key
    - name: S3_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: graal-prod-app-access-key
          key: bucket_secret_key
    - name: S3_REGION
      valueFrom:
        secretKeyRef:
          name: graal-prod-app-access-key
          key: bucket_region
    - name: USE_S3_CONFIG
      value: "true"