/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Health Check
     * @description Health check endpoint.
     *
     *     Returns the current status and timestamp of the API.
     */
    get: operations['health_check_api_v1_health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/config-files': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Config Files
     * @description List available configuration files from S3.
     *
     *     Returns:
     *         ConfigFilesResponse with list of available configuration files
     *
     *     Raises:
     *         HTTPException: 503 if S3 is not available, 500 for other errors
     */
    get: operations['list_config_files_api_v1_config_files_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/similarity-databases': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Similarity Databases
     * @description List available similarity database files from S3.
     *
     *     Returns:
     *         SimilarityDatabasesResponse with list of available database files
     *
     *     Raises:
     *         HTTPException: 503 if S3 is not available, 500 for other errors
     */
    get: operations['list_similarity_databases_api_v1_similarity_databases_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/process': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Process Amendments
     * @description Upload and process a JSON file containing amendments.
     *
     *     Args:
     *         file: JSON file containing amendments data
     *         request: JSON string containing ProcessingRequest data (see ProcessingRequest model)
     *
     *     Returns:
     *         ProcessingResponse with job_id and initial status
     *
     *     Raises:
     *         HTTPException: 400 for validation errors, 413 for file too large, 422 for invalid JSON
     *
     *     Example request JSON:
     *         {
     *             "processing_config": {
     *                 "origin_project": "PLF 2025",
     *                 "allotment": {
     *                     "enabled": true,
     *                     "column": "Corps amdt",
     *                     "similarity_threshold": 0.999
     *                 },
     *                 "similarities_within_lectures": {
     *                     "enabled": false,
     *                     "column": "Exposé amdt",
     *                     "similarity_threshold": 0.8
     *                 },
     *                 "similarity_search": {
     *                     "enabled": false
     *                 },
     *                 "attribution": {
     *                     "enabled": true,
     *                     "project_name": "PLF"
     *                 },
     *                 "default_opinion": {
     *                     "enabled": false
     *                 }
     *             }
     *         }
     */
    post: operations['process_amendments_api_v1_process_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/status/{job_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Processing Status
     * @description Get the current processing status of a job.
     *
     *     Args:
     *         job_id: Unique job identifier
     *
     *     Returns:
     *         ProgressResponse with current status and progress
     *
     *     Raises:
     *         HTTPException: 404 if job not found
     */
    get: operations['get_processing_status_api_v1_status__job_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/results/{job_id}/preview': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Results Preview
     * @description Get a preview of the processing results (first 10 rows).
     *
     *     Args:
     *         job_id: Unique job identifier
     *
     *     Returns:
     *         PreviewResponse with first 10 rows of results
     *
     *     Raises:
     *         HTTPException: 404 if job not found, 400 if job not completed
     */
    get: operations['get_results_preview_api_v1_results__job_id__preview_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/results/{job_id}/download': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Download Results
     * @description Download the complete processing results as a CSV file.
     *
     *     Args:
     *         job_id: Unique job identifier
     *
     *     Returns:
     *         CSV file download
     *
     *     Raises:
     *         HTTPException: 404 if job not found, 400 if job not completed
     */
    get: operations['download_results_api_v1_results__job_id__download_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/results/{job_id}/download/excel': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Download Excel Results
     * @description Download the complete processing results as an Excel file.
     *
     *     Args:
     *         job_id: Unique job identifier
     *
     *     Returns:
     *         Excel file download
     *
     *     Raises:
     *         HTTPException: 404 if job not found, 400 if job not completed
     */
    get: operations['download_excel_results_api_v1_results__job_id__download_excel_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/databases': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Databases
     * @description List all available similarity databases from S3.
     *
     *     Returns:
     *         DatabaseListResponse: List of available databases with metadata
     *
     *     Raises:
     *         HTTPException: 500 if listing fails
     */
    get: operations['list_databases_api_v1_databases_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/databases/upload-file': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Upload Amendment File
     * @description Upload an amendment file for database building.
     *
     *     The file is checked against the pool using hash-based deduplication.
     *     If the file already exists, returns reference to existing file.
     *     Otherwise uploads to pool and returns new file reference.
     *
     *     Args:
     *         file: The amendment file to upload
     *         metadata: JSON string with required default_processing_timestamp and origin_project
     *
     *     Returns:
     *         FileUploadResponse: Upload information including hash, s3_key, and deduplication status
     *
     *     Raises:
     *         HTTPException: 500 if upload fails
     */
    post: operations['upload_amendment_file_api_v1_databases_upload_file_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/databases/build': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Build Database
     * @description Start building a similarity database in the background.
     *
     *     Args:
     *         request: DatabaseBuildRequest with build configuration
     *
     *     Returns:
     *         ProcessingResponse: Job information for tracking build progress
     *
     *     Raises:
     *         HTTPException: 400 for validation errors, 500 for build errors
     *
     *     Example request:
     *         {
     *             "config_file": "Fichier de configuration GRAAL - DSS - latest.xlsx",
     *             "database_name": "PLFSS_2024",
     *             "files_metadata": [
     *                 {
     *                     "filename": "amendments_2024.json",
     *                     "default_processing_timestamp": 1704067200,
     *                     "origin_project": "PLFSS 2024"
     *                 }
     *             ],
     *             "drop_empty_columns": ["Réponse"],
     *             "similarity_threshold": 0.99,
     *             "eps": 0.4,
     *             "group_by_columns": ["Lecture", "origin_project", "Num article"]
     *         }
     */
    post: operations['build_database_api_v1_databases_build_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/databases/uploads/{upload_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Delete Uploaded File
     * @description Delete an uploaded file that's no longer needed.
     *
     *     This endpoint is idempotent - if the file doesn't exist, it returns success
     *     since the desired state (file not existing) is already achieved.
     *
     *     Args:
     *         upload_id: The upload ID of the file to delete
     *
     *     Returns:
     *         dict: Success message
     *
     *     Raises:
     *         HTTPException: 500 if deletion fails
     */
    delete: operations['delete_uploaded_file_api_v1_databases_uploads__upload_id__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/databases/{database_name}/append': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Append To Database
     * @description Append new files to an existing database by rebuilding with all files.
     *
     *     This endpoint loads the existing database manifest, combines the existing files
     *     with the new file references, and triggers a full rebuild of the database.
     *
     *     Args:
     *         database_name: Name of the database to append to
     *         request: AppendDatabaseRequest with new files and build configuration
     *
     *     Returns:
     *         ProcessingResponse: Job information for tracking append progress
     */
    post: operations['append_to_database_api_v1_databases__database_name__append_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/databases/{database_name}/manifest': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Database Manifest
     * @description Retrieve the manifest for a database showing all input files.
     *
     *     Args:
     *         database_name: Name of the database
     *
     *     Returns:
     *         DatabaseManifestResponse: Manifest with list of files and metadata
     *
     *     Raises:
     *         HTTPException: 404 if database/manifest not found, 500 for other errors
     */
    get: operations['get_database_manifest_api_v1_databases__database_name__manifest_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Current User
     * @description Get current authenticated user information, including admin status.
     *
     *     This endpoint serves dual purposes:
     *     1. Retrieve user information (user_id, email)
     *     2. Check admin privileges via the is_admin field
     *
     *     Frontend should use this single endpoint for all authentication checks.
     *
     *     Returns:
     *         UserResponse with user details including admin status
     *
     *     Raises:
     *         HTTPException: 500 if failed to retrieve user information
     */
    get: operations['get_current_user_api_v1_auth_me_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * AmendmentPreview
     * @description Model for a single amendment in preview results.
     */
    AmendmentPreview: {
      /** Num Amdt */
      num_amdt?: string | null
      /** Commentaires */
      commentaires?: string | null
      /** Allotissement */
      allotissement?: string | null
      /** Objet Amdt */
      objet_amdt?: string | null
      /** Sort */
      sort?: string | null
      /** Reponse */
      reponse?: string | null
      /** Affectation Email */
      affectation_email?: string | null
      /** Affectation Nom */
      affectation_nom?: string | null
      /** Entite Pilote */
      entite_pilote?: string | null
      /** Avis Du Gouvernement */
      avis_du_gouvernement?: string | null
      /** Groupe */
      groupe?: string | null
      /** Num Article */
      num_article?: string | null
      /** Expose Amdt */
      expose_amdt?: string | null
      /** Corps Amdt */
      corps_amdt?: string | null
      /** Mission */
      mission?: string | null
    }
    /**
     * AppendDatabaseRequest
     * @description Request to append files to an existing database.
     */
    AppendDatabaseRequest: {
      /**
       * Drop Empty Columns
       * @description Columns where empty rows should be dropped
       * @default [
       *       "Réponse"
       *     ]
       */
      drop_empty_columns: string[]
      /**
       * Similarity Threshold
       * @description Threshold for Levenshtein refinement
       * @default 0.99
       */
      similarity_threshold: number
      /**
       * Eps
       * @description Epsilon value for DBSCAN clustering
       * @default 0.4
       */
      eps: number
      /**
       * Group By Columns
       * @description Columns to group by during clustering
       * @default [
       *       "Lecture",
       *       "origin_project",
       *       "Num article"
       *     ]
       */
      group_by_columns: string[]
      /**
       * Config File
       * @description Office configuration Excel file to use
       */
      config_file: string
      /**
       * File References
       * @description References to new files to append
       */
      file_references: components['schemas']['FileUploadReference'][]
    }
    /** Body_process_amendments_api_v1_process_post */
    Body_process_amendments_api_v1_process_post: {
      /**
       * File
       * Format: binary
       */
      file: string
      /** Request */
      request: string
    }
    /** Body_upload_amendment_file_api_v1_databases_upload_file_post */
    Body_upload_amendment_file_api_v1_databases_upload_file_post: {
      /**
       * File
       * Format: binary
       */
      file: string
      /** Metadata */
      metadata: string
    }
    /**
     * ConfigFilesResponse
     * @description Response model for available configuration files.
     */
    ConfigFilesResponse: {
      /**
       * Files
       * @description List of available configuration file names
       */
      files: string[]
      /**
       * Total
       * @description Total number of available files
       */
      total: number
    }
    /**
     * DatabaseBuildRequest
     * @description Request to build a similarity database.
     */
    DatabaseBuildRequest: {
      /**
       * Drop Empty Columns
       * @description Columns where empty rows should be dropped
       * @default [
       *       "Réponse"
       *     ]
       */
      drop_empty_columns: string[]
      /**
       * Similarity Threshold
       * @description Threshold for Levenshtein refinement
       * @default 0.99
       */
      similarity_threshold: number
      /**
       * Eps
       * @description Epsilon value for DBSCAN clustering
       * @default 0.4
       */
      eps: number
      /**
       * Group By Columns
       * @description Columns to group by during clustering
       * @default [
       *       "Lecture",
       *       "origin_project",
       *       "Num article"
       *     ]
       */
      group_by_columns: string[]
      /**
       * Config File
       * @description Office configuration Excel file to use
       */
      config_file: string
      /**
       * Database Name
       * @description Name for the database (without extension)
       */
      database_name: string
      /**
       * File References
       * @description References to uploaded files
       */
      file_references: components['schemas']['FileUploadReference'][]
    }
    /**
     * DatabaseInfo
     * @description Information about a similarity database.
     */
    DatabaseInfo: {
      /**
       * Name
       * @description Database name (without extension)
       */
      name: string
      /**
       * Size Bytes
       * @description File size in bytes
       */
      size_bytes: number
      /**
       * Last Modified
       * Format: date-time
       * @description Last modification timestamp
       */
      last_modified: string
    }
    /**
     * DatabaseListResponse
     * @description Response containing list of available databases.
     */
    DatabaseListResponse: {
      /**
       * Databases
       * @description List of databases
       */
      databases: components['schemas']['DatabaseInfo'][]
      /**
       * Total
       * @description Total number of databases
       */
      total: number
    }
    /**
     * DatabaseManifestResponse
     * @description Response model for database manifest.
     */
    DatabaseManifestResponse: {
      /**
       * Database Name
       * @description Name of the database
       */
      database_name: string
      /**
       * Created At
       * @description ISO 8601 timestamp when database was created
       */
      created_at: string
      /**
       * Last Updated At
       * @description ISO 8601 timestamp when database was last updated
       */
      last_updated_at: string
      /**
       * Files
       * @description List of files in database
       */
      files: components['schemas']['FileReferenceInfo'][]
      /**
       * Total Files
       * @description Total number of files
       */
      total_files: number
    }
    /**
     * FileReferenceInfo
     * @description Information about a file in a database manifest.
     */
    FileReferenceInfo: {
      /**
       * Upload Id
       * @description Upload ID (derived from hash for UI compatibility)
       */
      upload_id: string
      /**
       * Filename
       * @description Original filename provided by user
       */
      filename: string
      /**
       * File Hash
       * @description SHA256 hash of file content
       */
      file_hash: string
      /**
       * S3 Key
       * @description S3 key in pool
       */
      s3_key: string
      /**
       * Uploaded At
       * @description ISO 8601 timestamp when file was uploaded
       */
      uploaded_at: string
      /**
       * Metadata
       * @description Processing metadata
       */
      metadata: Record<string, never>
    }
    /**
     * FileUploadMetadata
     * @description Metadata for file upload operations.
     */
    FileUploadMetadata: {
      /**
       * Default Processing Timestamp
       * @description Unix timestamp for processing
       */
      default_processing_timestamp: number
      /**
       * Origin Project
       * @description Origin project name
       */
      origin_project: string
    }
    /**
     * FileUploadReference
     * @description Reference to an uploaded file.
     */
    FileUploadReference: {
      /**
       * Upload Id
       * @description Upload ID from file upload
       */
      upload_id: string
      /**
       * Filename
       * @description Original filename
       */
      filename: string
      /**
       * File Hash
       * @description SHA256 hash of file content
       */
      file_hash: string
      /**
       * S3 Key
       * @description S3 key where file is stored in pool
       */
      s3_key: string
      /** @description File processing metadata */
      metadata: components['schemas']['FileUploadMetadata']
    }
    /**
     * FileUploadResponse
     * @description Response model for file upload.
     */
    FileUploadResponse: {
      /**
       * Upload Id
       * @description Unique upload identifier
       */
      upload_id: string
      /**
       * Filename
       * @description Original filename
       */
      filename: string
      /**
       * File Hash
       * @description SHA256 hash of file content
       */
      file_hash: string
      /**
       * S3 Key
       * @description S3 key where file is stored in pool
       */
      s3_key: string
      /**
       * Already Existed
       * @description True if file already existed in pool (deduplicated)
       */
      already_existed: boolean
      /**
       * Size
       * @description File size in bytes
       */
      size: number
      /**
       * Metadata
       * @description Processing metadata
       */
      metadata: Record<string, never>
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /**
     * JobStatus
     * @description Job processing status enumeration.
     * @enum {string}
     */
    JobStatus: 'queued' | 'running' | 'completed' | 'failed' | 'timeout'
    /**
     * PreviewResponse
     * @description Response model for results preview.
     */
    PreviewResponse: {
      /** Job Id */
      job_id: string
      /** Total Rows */
      total_rows: number
      /** Preview Rows */
      preview_rows: components['schemas']['AmendmentPreview'][]
      /** Columns */
      columns: string[]
    }
    /**
     * ProcessingResponse
     * @description Response model for processing job creation.
     */
    ProcessingResponse: {
      /** Job Id */
      job_id: string
      status: components['schemas']['JobStatus']
      /** Message */
      message: string
    }
    /**
     * ProgressResponse
     * @description Response model for job progress status.
     */
    ProgressResponse: {
      /** Job Id */
      job_id: string
      status: components['schemas']['JobStatus']
      /** Percent */
      percent: number
      /** Message */
      message?: string | null
      /**
       * Started At
       * Format: date-time
       */
      started_at: string
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string
    }
    /**
     * SimilarityDatabasesResponse
     * @description Response model for available similarity database files.
     */
    SimilarityDatabasesResponse: {
      /**
       * Databases
       * @description List of available similarity database file paths (relative to similarity folder)
       */
      databases: string[]
      /**
       * Total
       * @description Total number of available database files
       */
      total: number
    }
    /**
     * UserResponse
     * @description Response model for user information.
     *
     *     This response includes the is_admin field, making it the single source
     *     for both user information and admin status checks.
     */
    UserResponse: {
      /**
       * User Id
       * @description Unique user identifier
       */
      user_id: string
      /**
       * Email
       * @description User email address
       */
      email?: string | null
      /**
       * Is Admin
       * @description Whether user has admin privileges
       */
      is_admin: boolean
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  health_check_api_v1_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
    }
  }
  list_config_files_api_v1_config_files_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ConfigFilesResponse']
        }
      }
    }
  }
  list_similarity_databases_api_v1_similarity_databases_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SimilarityDatabasesResponse']
        }
      }
    }
  }
  process_amendments_api_v1_process_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['Body_process_amendments_api_v1_process_post']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProcessingResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_processing_status_api_v1_status__job_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        job_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProgressResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_results_preview_api_v1_results__job_id__preview_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        job_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PreviewResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  download_results_api_v1_results__job_id__download_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        job_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  download_excel_results_api_v1_results__job_id__download_excel_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        job_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_databases_api_v1_databases_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DatabaseListResponse']
        }
      }
    }
  }
  upload_amendment_file_api_v1_databases_upload_file_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['Body_upload_amendment_file_api_v1_databases_upload_file_post']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['FileUploadResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  build_database_api_v1_databases_build_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['DatabaseBuildRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProcessingResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_uploaded_file_api_v1_databases_uploads__upload_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        upload_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  append_to_database_api_v1_databases__database_name__append_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        database_name: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AppendDatabaseRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProcessingResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_database_manifest_api_v1_databases__database_name__manifest_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        database_name: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DatabaseManifestResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_current_user_api_v1_auth_me_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserResponse']
        }
      }
    }
  }
}
