/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint.
         *
         *     Returns the current status and timestamp of the API.
         */
        get: operations["health_check_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Process Amendments
         * @description Upload and process a JSON file containing amendments.
         *
         *     Args:
         *         file: JSON file containing amendments data
         *         request: JSON string containing ProcessingRequest data
         *
         *     Returns:
         *         ProcessingResponse with job_id and initial status
         *
         *     Raises:
         *         HTTPException: 400 for validation errors, 413 for file too large, 422 for invalid JSON
         */
        post: operations["process_amendments_api_v1_process_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/status/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Processing Status
         * @description Get the current processing status of a job.
         *
         *     Args:
         *         job_id: Unique job identifier
         *
         *     Returns:
         *         ProgressResponse with current status and progress
         *
         *     Raises:
         *         HTTPException: 404 if job not found
         */
        get: operations["get_processing_status_api_v1_status__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/results/{job_id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Results Preview
         * @description Get a preview of the processing results (first 10 rows).
         *
         *     Args:
         *         job_id: Unique job identifier
         *
         *     Returns:
         *         PreviewResponse with first 10 rows of results
         *
         *     Raises:
         *         HTTPException: 404 if job not found, 400 if job not completed
         */
        get: operations["get_results_preview_api_v1_results__job_id__preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/results/{job_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Results
         * @description Download the complete processing results as a CSV file.
         *
         *     Args:
         *         job_id: Unique job identifier
         *
         *     Returns:
         *         CSV file download
         *
         *     Raises:
         *         HTTPException: 404 if job not found, 400 if job not completed
         */
        get: operations["download_results_api_v1_results__job_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/results/{job_id}/download/excel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Excel Results
         * @description Download the complete processing results as an Excel file.
         *
         *     Args:
         *         job_id: Unique job identifier
         *
         *     Returns:
         *         Excel file download
         *
         *     Raises:
         *         HTTPException: 404 if job not found, 400 if job not completed
         */
        get: operations["download_excel_results_api_v1_results__job_id__download_excel_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AmendmentPreview
         * @description Model for a single amendment in preview results.
         */
        AmendmentPreview: {
            /** Num Amdt */
            num_amdt?: string | null;
            /** Commentaires */
            commentaires?: string | null;
            /** Allotissement */
            allotissement?: string | null;
            /** Objet Amdt */
            objet_amdt?: string | null;
            /** Sort */
            sort?: string | null;
            /** Reponse */
            reponse?: string | null;
            /** Affectation Email */
            affectation_email?: string | null;
            /** Affectation Nom */
            affectation_nom?: string | null;
            /** Entite Pilote */
            entite_pilote?: string | null;
            /** Avis Du Gouvernement */
            avis_du_gouvernement?: string | null;
            /** Groupe */
            groupe?: string | null;
            /** Num Article */
            num_article?: string | null;
            /** Expose Amdt */
            expose_amdt?: string | null;
            /** Corps Amdt */
            corps_amdt?: string | null;
            /** Mission */
            mission?: string | null;
        };
        /** Body_process_amendments_api_v1_process_post */
        Body_process_amendments_api_v1_process_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
            /** Request */
            request: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * JobStatus
         * @description Job processing status enumeration.
         * @enum {string}
         */
        JobStatus: "queued" | "running" | "completed" | "failed" | "timeout";
        /**
         * PreviewResponse
         * @description Response model for results preview.
         */
        PreviewResponse: {
            /** Job Id */
            job_id: string;
            /** Total Rows */
            total_rows: number;
            /** Preview Rows */
            preview_rows: components["schemas"]["AmendmentPreview"][];
            /** Columns */
            columns: string[];
        };
        /**
         * ProcessingResponse
         * @description Response model for processing job creation.
         */
        ProcessingResponse: {
            /** Job Id */
            job_id: string;
            status: components["schemas"]["JobStatus"];
            /** Message */
            message: string;
        };
        /**
         * ProgressResponse
         * @description Response model for job progress status.
         */
        ProgressResponse: {
            /** Job Id */
            job_id: string;
            status: components["schemas"]["JobStatus"];
            /** Percent */
            percent: number;
            /** Message */
            message?: string | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    process_amendments_api_v1_process_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_process_amendments_api_v1_process_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_processing_status_api_v1_status__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_results_preview_api_v1_results__job_id__preview_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_results_api_v1_results__job_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_excel_results_api_v1_results__job_id__download_excel_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
