/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Health Check
     * @description Health check endpoint.
     *
     *     Returns the current status and timestamp of the API.
     */
    get: operations['health_check_api_v1_health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/config-files': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Config Files
     * @description List available configuration files from S3.
     *
     *     Returns:
     *         ConfigFilesResponse with list of available configuration files
     *
     *     Raises:
     *         HTTPException: 503 if S3 is not available, 500 for other errors
     */
    get: operations['list_config_files_api_v1_config_files_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/process': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Process Amendments
     * @description Upload and process a JSON file containing amendments.
     *
     *     Args:
     *         file: JSON file containing amendments data
     *         request: JSON string containing ProcessingRequest data (see ProcessingRequest model)
     *
     *     Returns:
     *         ProcessingResponse with job_id and initial status
     *
     *     Raises:
     *         HTTPException: 400 for validation errors, 413 for file too large, 422 for invalid JSON
     *
     *     Example request JSON:
     *         {
     *             "processing_config": {
     *                 "origin_project": "PLF 2025",
     *                 "allotment": {
     *                     "enabled": true,
     *                     "column": "Corps amdt",
     *                     "similarity_threshold": 0.999
     *                 },
     *                 "similarities_within_lectures": {
     *                     "enabled": false,
     *                     "column": "Exposé amdt",
     *                     "similarity_threshold": 0.8
     *                 },
     *                 "similarity_search": {
     *                     "enabled": false
     *                 },
     *                 "attribution": {
     *                     "enabled": true,
     *                     "project_name": "PLF"
     *                 },
     *                 "default_opinion": {
     *                     "enabled": false
     *                 }
     *             }
     *         }
     */
    post: operations['process_amendments_api_v1_process_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/status/{job_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Processing Status
     * @description Get the current processing status of a job.
     *
     *     Args:
     *         job_id: Unique job identifier
     *
     *     Returns:
     *         ProgressResponse with current status and progress
     *
     *     Raises:
     *         HTTPException: 404 if job not found
     */
    get: operations['get_processing_status_api_v1_status__job_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/results/{job_id}/preview': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Results Preview
     * @description Get a preview of the processing results (first 10 rows).
     *
     *     Args:
     *         job_id: Unique job identifier
     *
     *     Returns:
     *         PreviewResponse with first 10 rows of results
     *
     *     Raises:
     *         HTTPException: 404 if job not found, 400 if job not completed
     */
    get: operations['get_results_preview_api_v1_results__job_id__preview_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/results/{job_id}/download': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Download Results
     * @description Download the complete processing results as a CSV file.
     *
     *     Args:
     *         job_id: Unique job identifier
     *
     *     Returns:
     *         CSV file download
     *
     *     Raises:
     *         HTTPException: 404 if job not found, 400 if job not completed
     */
    get: operations['download_results_api_v1_results__job_id__download_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/results/{job_id}/download/excel': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Download Excel Results
     * @description Download the complete processing results as an Excel file.
     *
     *     Args:
     *         job_id: Unique job identifier
     *
     *     Returns:
     *         Excel file download
     *
     *     Raises:
     *         HTTPException: 404 if job not found, 400 if job not completed
     */
    get: operations['download_excel_results_api_v1_results__job_id__download_excel_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/databases': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Databases
     * @description List all available similarity databases from PostgreSQL manifests.
     *
     *     Returns:
     *         DatabaseListResponse: List of available databases with metadata
     *
     *     Raises:
     *         HTTPException: 500 if listing fails
     */
    get: operations['list_databases_api_v1_databases_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/databases/upload-file': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Upload Amendment File
     * @description Upload an amendment file for database building.
     *
     *     The file is checked against the pool using hash-based deduplication.
     *     If the file already exists, returns reference to existing file.
     *     Otherwise uploads to pool and returns new file reference.
     *
     *     Args:
     *         file: The amendment file to upload
     *         metadata: JSON string with required default_processing_timestamp and origin_project
     *
     *     Returns:
     *         FileUploadResponse: Upload information including hash, s3_key, and deduplication status
     *
     *     Raises:
     *         HTTPException: 500 if upload fails
     */
    post: operations['upload_amendment_file_api_v1_databases_upload_file_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/databases/build': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Build Database
     * @description Start building a similarity database in the background.
     *
     *     Args:
     *         request: DatabaseBuildRequest with build configuration
     *         http_request: FastAPI request object
     *         session: Session cookie value
     *
     *     Returns:
     *         ProcessingResponse: Job information for tracking build progress
     *
     *     Raises:
     *         HTTPException: 401 if not authenticated, 400 for validation errors, 500 for build errors
     *
     *     Example request:
     *         {
     *             "config_file": "Fichier de configuration GRAAL - DSS - latest.xlsx",
     *             "database_name": "PLFSS_2024",
     *             "files_metadata": [
     *                 {
     *                     "filename": "amendments_2024.json",
     *                     "default_processing_timestamp": 1704067200,
     *                     "origin_project": "PLFSS 2024"
     *                 }
     *             ],
     *             "drop_empty_columns": ["Réponse"],
     *             "similarity_threshold": 0.99,
     *             "eps": 0.4,
     *             "group_by_columns": ["Lecture", "origin_project", "Num article"]
     *         }
     */
    post: operations['build_database_api_v1_databases_build_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/databases/uploads/{upload_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Delete Uploaded File
     * @description Delete an uploaded file that's no longer needed.
     *
     *     This endpoint is idempotent - if the file doesn't exist, it returns success
     *     since the desired state (file not existing) is already achieved.
     *
     *     Args:
     *         upload_id: The upload ID of the file to delete
     *
     *     Returns:
     *         dict: Success message
     *
     *     Raises:
     *         HTTPException: 500 if deletion fails
     */
    delete: operations['delete_uploaded_file_api_v1_databases_uploads__upload_id__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/databases/{database_name}/append': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Append To Database
     * @description Append new files to an existing database by rebuilding with all files.
     *
     *     This endpoint loads the existing database manifest, combines the existing files
     *     with the new file references, and triggers a full rebuild of the database.
     *
     *     Args:
     *         database_name: Name of the database to append to
     *         request: AppendDatabaseRequest with new files and build configuration
     *         http_request: FastAPI request object
     *         session: Session cookie value
     *
     *     Returns:
     *         ProcessingResponse: Job information for tracking append progress
     */
    post: operations['append_to_database_api_v1_databases__database_name__append_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/databases/{database_name}/manifest': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Database Manifest
     * @description Retrieve the manifest for a database showing all input files.
     *
     *     Args:
     *         database_name: Name of the database
     *
     *     Returns:
     *         DatabaseManifestResponse: Manifest with list of files and metadata
     *
     *     Raises:
     *         HTTPException: 404 if database/manifest not found, 500 for other errors
     */
    get: operations['get_database_manifest_api_v1_databases__database_name__manifest_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Current User
     * @description Get current authenticated user information, including admin status.
     *
     *     This endpoint serves dual purposes:
     *     1. Retrieve user information (user_id, email)
     *     2. Check admin privileges via the is_admin field
     *
     *     Frontend should use this single endpoint for all authentication checks.
     *
     *     Returns:
     *         UserResponse with user details including admin status
     *
     *     Raises:
     *         HTTPException: 500 if failed to retrieve user information
     */
    get: operations['get_current_user_api_v1_auth_me_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Login
     * @description Initiate ProConnect OAuth login flow.
     *
     *     This endpoint generates an authorization URL with state and PKCE parameters,
     *     stores them for validation, and redirects the user to ProConnect.
     *
     *     Returns:
     *         RedirectResponse to ProConnect authorization endpoint
     *
     *     Raises:
     *         HTTPException: 500 if OAuth initialization fails
     */
    get: operations['login_api_v1_auth_login_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/callback': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Callback
     * @description Handle ProConnect OAuth callback.
     *
     *     This endpoint:
     *     1. Validates the state parameter (CSRF protection)
     *     2. Exchanges authorization code for tokens
     *     3. Retrieves user claims from ProConnect
     *     4. Creates or updates user in database
     *     5. Creates session token
     *     6. Sets HTTP-only secure cookie
     *     7. Redirects to frontend
     *
     *     Args:
     *         code: Authorization code from ProConnect
     *         state: State parameter for CSRF validation
     *
     *     Returns:
     *         RedirectResponse to frontend with session cookie
     *
     *     Raises:
     *         HTTPException: 400 if invalid state or code
     *         HTTPException: 500 if authentication fails
     */
    get: operations['callback_api_v1_auth_callback_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Logout
     * @description Logout current user by clearing session cookie.
     *
     *     Args:
     *         response: FastAPI response object
     *         session: Session cookie value (optional)
     *
     *     Returns:
     *         Success message
     */
    post: operations['logout_api_v1_auth_logout_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/users/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get My Profile
     * @description Get current user's profile.
     *
     *     This endpoint returns the full profile of the authenticated user,
     *     including their admin status.
     *
     *     Args:
     *         request: FastAPI request object
     *         session: Session cookie value
     *
     *     Returns:
     *         UserResponse with user profile
     *
     *     Raises:
     *         HTTPException: 401 if not authenticated
     */
    get: operations['get_my_profile_api_v1_users_me_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/admin/users': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Users
     * @description List all users (admin only).
     *
     *     This endpoint returns a paginated list of all users in the system.
     *     Only accessible by administrators.
     *
     *     Args:
     *         request: FastAPI request object
     *         session: Session cookie value
     *         page: Page number (1-indexed)
     *         page_size: Number of users per page (max 100)
     *
     *     Returns:
     *         UserListResponse with paginated user list
     *
     *     Raises:
     *         HTTPException: 401 if not authenticated
     *         HTTPException: 403 if not admin
     */
    get: operations['list_users_api_v1_admin_users_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/admin/users/{user_id}/admin': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /**
     * Toggle Admin Status
     * @description Toggle admin status for a user (admin only).
     *
     *     This endpoint allows administrators to grant or revoke admin privileges
     *     for other users. Administrators cannot remove their own admin status.
     *
     *     Args:
     *         user_id: UUID of the user to modify
     *         toggle_request: Request body with new admin status
     *         request: FastAPI request object
     *         session: Session cookie value
     *
     *     Returns:
     *         UserResponse with updated user information
     *
     *     Raises:
     *         HTTPException: 401 if not authenticated
     *         HTTPException: 403 if not admin or trying to modify own status
     *         HTTPException: 404 if user not found
     */
    patch: operations['toggle_admin_status_api_v1_admin_users__user_id__admin_patch']
    trace?: never
  }
  '/api/v1/users/me/configurations': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List User Configurations
     * @description List all configurations for the current user.
     *
     *     Returns configurations ordered by creation date (newest first).
     *
     *     Args:
     *         request: FastAPI request object
     *         session: Session cookie value
     *
     *     Returns:
     *         List of UserConfigurationRead schemas
     *
     *     Raises:
     *         HTTPException: 401 if not authenticated
     */
    get: operations['list_user_configurations_api_v1_users_me_configurations_get']
    put?: never
    /**
     * Create User Configuration
     * @description Create a new configuration for the current user.
     *
     *     Validates that the S3 config file exists before creating.
     *     If is_default is True, unsets all other default configurations.
     *
     *     Args:
     *         config: Configuration data to create
     *         request: FastAPI request object
     *         session: Session cookie value
     *
     *     Returns:
     *         Created UserConfigurationRead schema
     *
     *     Raises:
     *         HTTPException: 401 if not authenticated
     *         HTTPException: 400 if S3 file validation fails
     */
    post: operations['create_user_configuration_api_v1_users_me_configurations_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/users/me/configurations/default': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Default Configuration
     * @description Get the user's default configuration.
     *
     *     Args:
     *         request: FastAPI request object
     *         session: Session cookie value
     *
     *     Returns:
     *         UserConfigurationRead schema of default configuration
     *
     *     Raises:
     *         HTTPException: 401 if not authenticated
     *         HTTPException: 404 if no default configuration set
     */
    get: operations['get_default_configuration_api_v1_users_me_configurations_default_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/users/me/configurations/{config_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get User Configuration
     * @description Get a specific configuration by ID.
     *
     *     Verifies that the configuration belongs to the current user.
     *
     *     Args:
     *         config_id: Configuration UUID
     *         request: FastAPI request object
     *         session: Session cookie value
     *
     *     Returns:
     *         UserConfigurationRead schema
     *
     *     Raises:
     *         HTTPException: 401 if not authenticated
     *         HTTPException: 404 if not found or doesn't belong to user
     */
    get: operations['get_user_configuration_api_v1_users_me_configurations__config_id__get']
    put?: never
    post?: never
    /**
     * Delete User Configuration
     * @description Delete a configuration.
     *
     *     Verifies ownership before deleting.
     *
     *     Args:
     *         config_id: Configuration UUID to delete
     *         request: FastAPI request object
     *         session: Session cookie value
     *
     *     Returns:
     *         204 No Content on success
     *
     *     Raises:
     *         HTTPException: 401 if not authenticated
     *         HTTPException: 404 if not found or doesn't belong to user
     */
    delete: operations['delete_user_configuration_api_v1_users_me_configurations__config_id__delete']
    options?: never
    head?: never
    /**
     * Update User Configuration
     * @description Update a configuration.
     *
     *     Verifies ownership before updating. If is_default is set to True,
     *     unsets all other default configurations. Validates S3 path if changed.
     *
     *     Args:
     *         config_id: Configuration UUID to update
     *         updates: Fields to update
     *         request: FastAPI request object
     *         session: Session cookie value
     *
     *     Returns:
     *         Updated UserConfigurationRead schema
     *
     *     Raises:
     *         HTTPException: 401 if not authenticated
     *         HTTPException: 404 if not found or doesn't belong to user
     *         HTTPException: 400 if S3 validation fails
     */
    patch: operations['update_user_configuration_api_v1_users_me_configurations__config_id__patch']
    trace?: never
  }
  '/api/v1/users/me/configurations/{config_id}/set-default': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Set Default Configuration
     * @description Set a configuration as the user's default.
     *
     *     Unsets all other default configurations before setting this one as default.
     *
     *     Args:
     *         config_id: Configuration UUID to set as default
     *         request: FastAPI request object
     *         session: Session cookie value
     *
     *     Returns:
     *         Updated UserConfigurationRead schema
     *
     *     Raises:
     *         HTTPException: 401 if not authenticated
     *         HTTPException: 404 if not found or doesn't belong to user
     */
    post: operations['set_default_configuration_api_v1_users_me_configurations__config_id__set_default_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/similarity-databases': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Similarity Databases
     * @description List all active similarity database manifests.
     *
     *     Available to all authenticated users.
     *
     *     Args:
     *         request: FastAPI request object
     *         session: Session cookie value
     *
     *     Returns:
     *         List of SimilarityDBManifestRead schemas
     *
     *     Raises:
     *         HTTPException: 401 if not authenticated
     */
    get: operations['list_similarity_databases_api_v1_similarity_databases_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/admin/similarity-databases/sync': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Sync Manifests From S3
     * @description Sync similarity database manifests from S3 (admin only).
     *
     *     Scans S3 for similarity database files and creates or updates
     *     manifests accordingly. This is typically run once to populate
     *     the database from existing S3 files.
     *
     *     Args:
     *         request: FastAPI request object
     *         session: Session cookie value
     *
     *     Returns:
     *         List of synced SimilarityDBManifestRead schemas
     *
     *     Raises:
     *         HTTPException: 401 if not authenticated
     *         HTTPException: 403 if not admin
     */
    post: operations['sync_manifests_from_s3_api_v1_admin_similarity_databases_sync_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/admin/similarity-databases': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Create Manifest
     * @description Manually create a similarity database manifest (admin only).
     *
     *     Validates that the S3 file exists before creating the manifest.
     *
     *     Args:
     *         manifest: Manifest data to create
     *         request: FastAPI request object
     *         session: Session cookie value
     *
     *     Returns:
     *         Created SimilarityDBManifestRead schema
     *
     *     Raises:
     *         HTTPException: 401 if not authenticated
     *         HTTPException: 403 if not admin
     *         HTTPException: 400 if S3 file validation fails
     */
    post: operations['create_manifest_api_v1_admin_similarity_databases_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/admin/similarity-databases/{manifest_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Delete Manifest
     * @description Deactivate a similarity database manifest (admin only, soft delete).
     *
     *     Sets the manifest's is_active flag to False. The manifest and its
     *     metadata remain in the database but won't appear in active listings.
     *
     *     Args:
     *         manifest_id: Manifest UUID to deactivate
     *         request: FastAPI request object
     *         session: Session cookie value
     *
     *     Returns:
     *         204 No Content on success
     *
     *     Raises:
     *         HTTPException: 401 if not authenticated
     *         HTTPException: 403 if not admin
     *         HTTPException: 404 if manifest not found
     */
    delete: operations['delete_manifest_api_v1_admin_similarity_databases__manifest_id__delete']
    options?: never
    head?: never
    /**
     * Update Manifest
     * @description Update a similarity database manifest (admin only).
     *
     *     Allows updating manifest metadata such as name, size, row count,
     *     and custom metadata.
     *
     *     Args:
     *         manifest_id: Manifest UUID to update
     *         updates: Fields to update
     *         request: FastAPI request object
     *         session: Session cookie value
     *
     *     Returns:
     *         Updated SimilarityDBManifestRead schema
     *
     *     Raises:
     *         HTTPException: 401 if not authenticated
     *         HTTPException: 403 if not admin
     *         HTTPException: 404 if manifest not found
     */
    patch: operations['update_manifest_api_v1_admin_similarity_databases__manifest_id__patch']
    trace?: never
  }
  '/api/v1/admin/s3/config-files': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Config Files
     * @description List all configuration files from S3.
     *
     *     Admin-only endpoint to view all available config files.
     *
     *     Returns:
     *         S3FileListResponse with list of config files and metadata
     *
     *     Raises:
     *         HTTPException: 403 if not admin, 500 if S3 operation fails
     */
    get: operations['list_config_files_api_v1_admin_s3_config_files_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/admin/s3/config-files/{filename}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Delete Config File
     * @description Delete a configuration file from S3.
     *
     *     Admin-only endpoint to delete config files.
     *
     *     Args:
     *         filename: Name of the config file to delete
     *
     *     Returns:
     *         S3DeleteResponse with deletion status
     *
     *     Raises:
     *         HTTPException: 403 if not admin, 404 if file not found, 500 if deletion fails
     */
    delete: operations['delete_config_file_api_v1_admin_s3_config_files__filename__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/admin/s3/databases': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Database Files
     * @description List all similarity database files from S3.
     *
     *     Admin-only endpoint to view all available similarity databases.
     *
     *     Returns:
     *         S3FileListResponse with list of database files and metadata
     *
     *     Raises:
     *         HTTPException: 403 if not admin, 500 if S3 operation fails
     */
    get: operations['list_database_files_api_v1_admin_s3_databases_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/admin/s3/databases/{database_name}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Delete Database File
     * @description Delete a similarity database file from S3.
     *
     *     Admin-only endpoint to delete database files.
     *
     *     Args:
     *         database_name: Name of the database to delete (without .parquet extension)
     *
     *     Returns:
     *         S3DeleteResponse with deletion status
     *
     *     Raises:
     *         HTTPException: 403 if not admin, 404 if database not found, 500 if deletion fails
     */
    delete: operations['delete_database_file_api_v1_admin_s3_databases__database_name__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/admin/s3/input-pool': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Input Pool Files
     * @description List all files in the input pool from S3.
     *
     *     Admin-only endpoint to view all uploaded files in the input pool.
     *
     *     Returns:
     *         S3FileListResponse with list of input pool files and metadata
     *
     *     Raises:
     *         HTTPException: 403 if not admin, 500 if S3 operation fails
     */
    get: operations['list_input_pool_files_api_v1_admin_s3_input_pool_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/admin/s3/input-pool/{s3_key}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Delete Input Pool File
     * @description Delete a file from the input pool in S3.
     *
     *     Admin-only endpoint to delete files from the input pool.
     *
     *     Args:
     *         s3_key: S3 key (path) of the file to delete
     *
     *     Returns:
     *         S3DeleteResponse with deletion status
     *
     *     Raises:
     *         HTTPException: 403 if not admin, 404 if file not found, 500 if deletion fails
     */
    delete: operations['delete_input_pool_file_api_v1_admin_s3_input_pool__s3_key__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * AmendmentPreview
     * @description Model for a single amendment in preview results.
     */
    AmendmentPreview: {
      /** Num Amdt */
      num_amdt?: string | null
      /** Commentaires */
      commentaires?: string | null
      /** Allotissement */
      allotissement?: string | null
      /** Objet Amdt */
      objet_amdt?: string | null
      /** Sort */
      sort?: string | null
      /** Reponse */
      reponse?: string | null
      /** Affectation Email */
      affectation_email?: string | null
      /** Affectation Nom */
      affectation_nom?: string | null
      /** Entite Pilote */
      entite_pilote?: string | null
      /** Avis Du Gouvernement */
      avis_du_gouvernement?: string | null
      /** Groupe */
      groupe?: string | null
      /** Num Article */
      num_article?: string | null
      /** Expose Amdt */
      expose_amdt?: string | null
      /** Corps Amdt */
      corps_amdt?: string | null
      /** Mission */
      mission?: string | null
    }
    /**
     * AppendDatabaseRequest
     * @description Request to append files to an existing database.
     */
    AppendDatabaseRequest: {
      /**
       * Drop Empty Columns
       * @description Columns where empty rows should be dropped
       * @default [
       *       "Réponse"
       *     ]
       */
      drop_empty_columns: string[]
      /**
       * Similarity Threshold
       * @description Threshold for Levenshtein refinement
       * @default 0.99
       */
      similarity_threshold: number
      /**
       * Eps
       * @description Epsilon value for DBSCAN clustering
       * @default 0.4
       */
      eps: number
      /**
       * Group By Columns
       * @description Columns to group by during clustering
       * @default [
       *       "Lecture",
       *       "origin_project",
       *       "Num article"
       *     ]
       */
      group_by_columns: string[]
      /**
       * Config File
       * @description Office configuration Excel file to use
       */
      config_file: string
      /**
       * File References
       * @description References to new files to append
       */
      file_references: components['schemas']['FileUploadReference'][]
    }
    /** Body_process_amendments_api_v1_process_post */
    Body_process_amendments_api_v1_process_post: {
      /**
       * File
       * Format: binary
       */
      file: string
      /** Request */
      request: string
    }
    /** Body_upload_amendment_file_api_v1_databases_upload_file_post */
    Body_upload_amendment_file_api_v1_databases_upload_file_post: {
      /**
       * File
       * Format: binary
       */
      file: string
      /** Metadata */
      metadata: string
    }
    /**
     * ConfigFilesResponse
     * @description Response model for available configuration files.
     */
    ConfigFilesResponse: {
      /**
       * Files
       * @description List of available configuration file names
       */
      files: string[]
      /**
       * Total
       * @description Total number of available files
       */
      total: number
    }
    /**
     * DatabaseBuildRequest
     * @description Request to build a similarity database.
     */
    DatabaseBuildRequest: {
      /**
       * Drop Empty Columns
       * @description Columns where empty rows should be dropped
       * @default [
       *       "Réponse"
       *     ]
       */
      drop_empty_columns: string[]
      /**
       * Similarity Threshold
       * @description Threshold for Levenshtein refinement
       * @default 0.99
       */
      similarity_threshold: number
      /**
       * Eps
       * @description Epsilon value for DBSCAN clustering
       * @default 0.4
       */
      eps: number
      /**
       * Group By Columns
       * @description Columns to group by during clustering
       * @default [
       *       "Lecture",
       *       "origin_project",
       *       "Num article"
       *     ]
       */
      group_by_columns: string[]
      /**
       * Config File
       * @description Office configuration Excel file to use
       */
      config_file: string
      /**
       * Database Name
       * @description Name for the database (without extension)
       */
      database_name: string
      /**
       * File References
       * @description References to uploaded files
       */
      file_references: components['schemas']['FileUploadReference'][]
    }
    /**
     * DatabaseInfo
     * @description Information about a similarity database.
     */
    DatabaseInfo: {
      /**
       * Name
       * @description Database name (without extension)
       */
      name: string
      /**
       * Size Bytes
       * @description File size in bytes
       */
      size_bytes: number
      /**
       * Last Modified
       * Format: date-time
       * @description Last modification timestamp
       */
      last_modified: string
    }
    /**
     * DatabaseListResponse
     * @description Response containing list of available databases.
     */
    DatabaseListResponse: {
      /**
       * Databases
       * @description List of databases
       */
      databases: components['schemas']['DatabaseInfo'][]
      /**
       * Total
       * @description Total number of databases
       */
      total: number
    }
    /**
     * DatabaseManifestResponse
     * @description Response model for database manifest.
     */
    DatabaseManifestResponse: {
      /**
       * Database Name
       * @description Name of the database
       */
      database_name: string
      /**
       * Created At
       * @description ISO 8601 timestamp when database was created
       */
      created_at: string
      /**
       * Last Updated At
       * @description ISO 8601 timestamp when database was last updated
       */
      last_updated_at: string
      /**
       * Files
       * @description List of files in database
       */
      files: components['schemas']['FileReferenceInfo'][]
      /**
       * Total Files
       * @description Total number of files
       */
      total_files: number
    }
    /**
     * FileReferenceInfo
     * @description Information about a file in a database manifest.
     */
    FileReferenceInfo: {
      /**
       * Upload Id
       * @description Upload ID (derived from hash for UI compatibility)
       */
      upload_id: string
      /**
       * Filename
       * @description Original filename provided by user
       */
      filename: string
      /**
       * File Hash
       * @description SHA256 hash of file content
       */
      file_hash: string
      /**
       * S3 Key
       * @description S3 key in pool
       */
      s3_key: string
      /**
       * Uploaded At
       * @description ISO 8601 timestamp when file was uploaded
       */
      uploaded_at: string
      /**
       * Metadata
       * @description Processing metadata
       */
      metadata: {
        [key: string]: unknown
      }
    }
    /**
     * FileUploadMetadata
     * @description Metadata for file upload operations.
     */
    FileUploadMetadata: {
      /**
       * Default Processing Timestamp
       * @description Unix timestamp for processing
       */
      default_processing_timestamp: number
      /**
       * Origin Project
       * @description Origin project name
       */
      origin_project: string
    }
    /**
     * FileUploadReference
     * @description Reference to an uploaded file.
     */
    FileUploadReference: {
      /**
       * Upload Id
       * @description Upload ID from file upload
       */
      upload_id: string
      /**
       * Filename
       * @description Original filename
       */
      filename: string
      /**
       * File Hash
       * @description SHA256 hash of file content
       */
      file_hash: string
      /**
       * S3 Key
       * @description S3 key where file is stored in pool
       */
      s3_key: string
      /** @description File processing metadata */
      metadata: components['schemas']['FileUploadMetadata']
    }
    /**
     * FileUploadResponse
     * @description Response model for file upload.
     */
    FileUploadResponse: {
      /**
       * Upload Id
       * @description Unique upload identifier
       */
      upload_id: string
      /**
       * Filename
       * @description Original filename
       */
      filename: string
      /**
       * File Hash
       * @description SHA256 hash of file content
       */
      file_hash: string
      /**
       * S3 Key
       * @description S3 key where file is stored in pool
       */
      s3_key: string
      /**
       * Already Existed
       * @description True if file already existed in pool (deduplicated)
       */
      already_existed: boolean
      /**
       * Size
       * @description File size in bytes
       */
      size: number
      /**
       * Metadata
       * @description Processing metadata
       */
      metadata: {
        [key: string]: unknown
      }
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /**
     * JobStatus
     * @description Job processing status enumeration.
     * @enum {string}
     */
    JobStatus: 'queued' | 'running' | 'completed' | 'failed' | 'timeout'
    /**
     * PreviewResponse
     * @description Response model for results preview.
     */
    PreviewResponse: {
      /** Job Id */
      job_id: string
      /** Total Rows */
      total_rows: number
      /** Preview Rows */
      preview_rows: components['schemas']['AmendmentPreview'][]
      /** Columns */
      columns: string[]
    }
    /**
     * ProcessingResponse
     * @description Response model for processing job creation.
     */
    ProcessingResponse: {
      /** Job Id */
      job_id: string
      status: components['schemas']['JobStatus']
      /** Message */
      message: string
    }
    /**
     * ProgressResponse
     * @description Response model for job progress status.
     */
    ProgressResponse: {
      /** Job Id */
      job_id: string
      status: components['schemas']['JobStatus']
      /** Percent */
      percent: number
      /** Message */
      message?: string | null
      /**
       * Started At
       * Format: date-time
       */
      started_at: string
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string
    }
    /**
     * S3DeleteResponse
     * @description Response model for S3 file deletion.
     */
    S3DeleteResponse: {
      /**
       * Success
       * @description Whether deletion was successful
       */
      success: boolean
      /**
       * Message
       * @description Success or error message
       */
      message: string
      /**
       * Deleted File
       * @description Name of deleted file
       */
      deleted_file: string
    }
    /**
     * S3FileListResponse
     * @description Response model for listing S3 files.
     */
    S3FileListResponse: {
      /**
       * Files
       * @description List of files with metadata
       */
      files: components['schemas']['S3FileMetadata'][]
      /**
       * Total Count
       * @description Total number of files
       */
      total_count: number
      /**
       * Folder
       * @description Folder name (config, database, input_pool)
       */
      folder: string
    }
    /**
     * S3FileMetadata
     * @description Model for S3 file metadata.
     */
    S3FileMetadata: {
      /**
       * Key
       * @description File name or S3 key
       */
      key: string
      /**
       * Size
       * @description File size in bytes
       */
      size: number
      /**
       * Last Modified
       * Format: date-time
       * @description Last modification timestamp
       */
      last_modified: string
      /**
       * File Type
       * @description Type of file (config, database, input_file)
       */
      file_type: string
    }
    /**
     * SimilarityDBManifestCreate
     * @description Schema for creating a new similarity database manifest.
     */
    SimilarityDBManifestCreate: {
      /**
       * Name
       * @description Database name
       */
      name: string
      /**
       * S3 Folder Path
       * @description S3 folder path
       */
      s3_folder_path: string
      /**
       * S3 File Path
       * @description Full S3 file path
       */
      s3_file_path: string
      /**
       * Size Bytes
       * @description File size in bytes
       */
      size_bytes: number
      /**
       * Row Count
       * @description Number of rows
       */
      row_count?: number | null
      /**
       * Db Metadata
       * @description Additional metadata
       */
      db_metadata?: {
        [key: string]: unknown
      } | null
      /**
       * Input Files
       * @description List of input files (replaces S3 manifest system)
       */
      input_files?: {
        [key: string]: unknown
      } | null
      /**
       * Last Modified
       * Format: date-time
       * @description S3 file last modified time
       */
      last_modified: string
    }
    /**
     * SimilarityDBManifestRead
     * @description Schema for reading similarity database manifest data.
     */
    SimilarityDBManifestRead: {
      /**
       * Name
       * @description Database name
       */
      name: string
      /**
       * S3 Folder Path
       * @description S3 folder path
       */
      s3_folder_path: string
      /**
       * S3 File Path
       * @description Full S3 file path
       */
      s3_file_path: string
      /**
       * Size Bytes
       * @description File size in bytes
       */
      size_bytes: number
      /**
       * Row Count
       * @description Number of rows
       */
      row_count?: number | null
      /**
       * Db Metadata
       * @description Additional metadata
       */
      db_metadata?: {
        [key: string]: unknown
      } | null
      /**
       * Input Files
       * @description List of input files (replaces S3 manifest system)
       */
      input_files?: {
        [key: string]: unknown
      } | null
      /**
       * Id
       * Format: uuid
       */
      id: string
      /**
       * Created By User Id
       * Format: uuid
       */
      created_by_user_id: string
      /**
       * Last Modified
       * Format: date-time
       */
      last_modified: string
      /** Is Active */
      is_active: boolean
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
    }
    /**
     * SimilarityDBManifestUpdate
     * @description Schema for updating a similarity database manifest.
     */
    SimilarityDBManifestUpdate: {
      /** Name */
      name?: string | null
      /** Size Bytes */
      size_bytes?: number | null
      /** Row Count */
      row_count?: number | null
      /** Last Modified */
      last_modified?: string | null
      /** Db Metadata */
      db_metadata?: {
        [key: string]: unknown
      } | null
      /** Input Files */
      input_files?: {
        [key: string]: unknown
      } | null
      /** Is Active */
      is_active?: boolean | null
    }
    /**
     * ToggleAdminRequest
     * @description Request model for toggling admin status.
     */
    ToggleAdminRequest: {
      /**
       * Is Admin
       * @description New admin status
       */
      is_admin: boolean
    }
    /**
     * UserConfigurationCreate
     * @description Schema for creating a new configuration.
     */
    UserConfigurationCreate: {
      /**
       * Name
       * @description Configuration name
       */
      name: string
      /**
       * Feature Settings
       * @description Feature settings
       */
      feature_settings: {
        [key: string]: unknown
      }
      /**
       * Is Default
       * @description Is default configuration
       * @default false
       */
      is_default: boolean
    }
    /**
     * UserConfigurationRead
     * @description Schema for reading configuration data.
     */
    UserConfigurationRead: {
      /**
       * Name
       * @description Configuration name
       */
      name: string
      /**
       * Feature Settings
       * @description Feature settings
       */
      feature_settings: {
        [key: string]: unknown
      }
      /**
       * Is Default
       * @description Is default configuration
       * @default false
       */
      is_default: boolean
      /**
       * Id
       * Format: uuid
       */
      id: string
      /**
       * User Id
       * Format: uuid
       */
      user_id: string
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string
    }
    /**
     * UserConfigurationUpdate
     * @description Schema for updating a configuration.
     */
    UserConfigurationUpdate: {
      /** Name */
      name?: string | null
      /** Feature Settings */
      feature_settings?: {
        [key: string]: unknown
      } | null
      /** Is Default */
      is_default?: boolean | null
    }
    /**
     * UserListResponse
     * @description Response model for paginated user list.
     */
    UserListResponse: {
      /**
       * Users
       * @description List of users
       */
      users: components['schemas']['UserResponse'][]
      /**
       * Total
       * @description Total number of users
       */
      total: number
      /**
       * Page
       * @description Current page number
       */
      page: number
      /**
       * Page Size
       * @description Number of users per page
       */
      page_size: number
    }
    /**
     * UserResponse
     * @description Response model for user information.
     *
     *     This response includes the is_admin field, making it the single source
     *     for both user information and admin status checks.
     */
    UserResponse: {
      /**
       * User Id
       * @description Unique user identifier
       */
      user_id: string
      /**
       * Email
       * @description User email address
       */
      email?: string | null
      /**
       * Is Admin
       * @description Whether user has admin privileges
       */
      is_admin: boolean
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  health_check_api_v1_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
    }
  }
  list_config_files_api_v1_config_files_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ConfigFilesResponse']
        }
      }
    }
  }
  process_amendments_api_v1_process_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: {
        session?: string | null
      }
    }
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['Body_process_amendments_api_v1_process_post']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProcessingResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_processing_status_api_v1_status__job_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        job_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProgressResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_results_preview_api_v1_results__job_id__preview_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        job_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PreviewResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  download_results_api_v1_results__job_id__download_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        job_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  download_excel_results_api_v1_results__job_id__download_excel_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        job_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_databases_api_v1_databases_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DatabaseListResponse']
        }
      }
    }
  }
  upload_amendment_file_api_v1_databases_upload_file_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['Body_upload_amendment_file_api_v1_databases_upload_file_post']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['FileUploadResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  build_database_api_v1_databases_build_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: {
        session?: string | null
      }
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['DatabaseBuildRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProcessingResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_uploaded_file_api_v1_databases_uploads__upload_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        upload_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  append_to_database_api_v1_databases__database_name__append_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        database_name: string
      }
      cookie?: {
        session?: string | null
      }
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AppendDatabaseRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProcessingResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_database_manifest_api_v1_databases__database_name__manifest_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        database_name: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DatabaseManifestResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_current_user_api_v1_auth_me_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: {
        session?: string | null
      }
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  login_api_v1_auth_login_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
    }
  }
  callback_api_v1_auth_callback_get: {
    parameters: {
      query: {
        code: string
        state: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  logout_api_v1_auth_logout_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: {
        session?: string | null
      }
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_my_profile_api_v1_users_me_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: {
        session?: string | null
      }
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_users_api_v1_admin_users_get: {
    parameters: {
      query?: {
        /** @description Page number */
        page?: number
        /** @description Users per page */
        page_size?: number
      }
      header?: never
      path?: never
      cookie?: {
        session?: string | null
      }
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserListResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  toggle_admin_status_api_v1_admin_users__user_id__admin_patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        user_id: string
      }
      cookie?: {
        session?: string | null
      }
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ToggleAdminRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_user_configurations_api_v1_users_me_configurations_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: {
        session?: string | null
      }
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserConfigurationRead'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_user_configuration_api_v1_users_me_configurations_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: {
        session?: string | null
      }
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UserConfigurationCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserConfigurationRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_default_configuration_api_v1_users_me_configurations_default_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: {
        session?: string | null
      }
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserConfigurationRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_user_configuration_api_v1_users_me_configurations__config_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        config_id: string
      }
      cookie?: {
        session?: string | null
      }
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserConfigurationRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_user_configuration_api_v1_users_me_configurations__config_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        config_id: string
      }
      cookie?: {
        session?: string | null
      }
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_user_configuration_api_v1_users_me_configurations__config_id__patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        config_id: string
      }
      cookie?: {
        session?: string | null
      }
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UserConfigurationUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserConfigurationRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  set_default_configuration_api_v1_users_me_configurations__config_id__set_default_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        config_id: string
      }
      cookie?: {
        session?: string | null
      }
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserConfigurationRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_similarity_databases_api_v1_similarity_databases_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: {
        session?: string | null
      }
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SimilarityDBManifestRead'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  sync_manifests_from_s3_api_v1_admin_similarity_databases_sync_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: {
        session?: string | null
      }
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SimilarityDBManifestRead'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_manifest_api_v1_admin_similarity_databases_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: {
        session?: string | null
      }
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SimilarityDBManifestCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SimilarityDBManifestRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_manifest_api_v1_admin_similarity_databases__manifest_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        manifest_id: string
      }
      cookie?: {
        session?: string | null
      }
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_manifest_api_v1_admin_similarity_databases__manifest_id__patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        manifest_id: string
      }
      cookie?: {
        session?: string | null
      }
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SimilarityDBManifestUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SimilarityDBManifestRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_config_files_api_v1_admin_s3_config_files_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: {
        session?: string | null
      }
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['S3FileListResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_config_file_api_v1_admin_s3_config_files__filename__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Configuration file name */
        filename: string
      }
      cookie?: {
        session?: string | null
      }
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['S3DeleteResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_database_files_api_v1_admin_s3_databases_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: {
        session?: string | null
      }
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['S3FileListResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_database_file_api_v1_admin_s3_databases__database_name__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Database name (without .parquet extension) */
        database_name: string
      }
      cookie?: {
        session?: string | null
      }
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['S3DeleteResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_input_pool_files_api_v1_admin_s3_input_pool_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: {
        session?: string | null
      }
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['S3FileListResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_input_pool_file_api_v1_admin_s3_input_pool__s3_key__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description S3 key of the file to delete */
        s3_key: string
      }
      cookie?: {
        session?: string | null
      }
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['S3DeleteResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
}
