kind: ConfigMap
apiVersion: v1
metadata:
  name: graal
data:
  DATA_FOLDER: "/app/data"
  ETALAB_API_KEY: "xxxxxxxxxxxxxxxxxxx"
  ETALAB_BASE_URL: "https://albert.api.etalab.gouv.fr/v1"
  ETALAB_MODEL_NAME: "meta-llama/Meta-Llama-3.1-70B-Instruct"
  S3_SIMILARITY_DB_FOLDER: "similarity_dbs"
  S3_CONFIG_FOLDER: "config_graal"
  S3_INPUT_POOL_FOLDER: "input_files/pool"
  PROCONNECT_DISCOVERY_URL: "https://fca.integ01.dev-agentconnect.fr/api/v2/.well-known/openid-configuration"
  PROCONNECT_SCOPES: "openid email profile"
  SESSION_MAX_AGE: "15552000"
  SECURE_COOKIES: "true"
  BACKEND_ENABLE_DEV_LOGIN: "true"
  VITE_ENABLE_DEV_LOGIN: "true"
