# BDD Amendements Configuration
# This file contains project configurations for amendment processing

projects:
  PLFSS:
    json_configs:
      - path: "exports_lectures/PLFSS 2021 JSON/lecture-senat-2020-2021-101-PO78718.json"
        default_processing_timestamp:
          year: 2020
          month: 7
          day: 1
        origin_project: "PLFSS 2021"
      - path: "exports_lectures/PLFSS 2021 JSON/lecture-an-15-3551-PO717460.json"
        default_processing_timestamp:
          year: 2020
          month: 7
          day: 1
        origin_project: "PLFSS 2021"
      - path: "exports_lectures/PLFSS 2021 JSON/lecture-an-15-3397-PO717460.json"
        default_processing_timestamp:
          year: 2020
          month: 7
          day: 1
        origin_project: "PLFSS 2021"
      - path: "exports_lectures/PLFSS 2021 JSON/lecture-an-15-3397-PO420120.json"
        default_processing_timestamp:
          year: 2020
          month: 7
          day: 1
        origin_project: "PLFSS 2021"
      - path: "exports_lectures/PLFSS 2022/lecture-senat-2021-2022-118-PO78718.json"
        default_processing_timestamp:
          year: 2021
          month: 7
          day: 1
        origin_project: "PLFSS 2022"
      - path: "exports_lectures/PLFSS 2022/lecture-senat-2021-2022-189-PO78718.json"
        default_processing_timestamp:
          year: 2021
          month: 7
          day: 1
        origin_project: "PLFSS 2022"
      - path: "exports_lectures/PLFSS 2022/lecture-an-15-4685-PO717460.json"
        default_processing_timestamp:
          year: 2021
          month: 7
          day: 1
        origin_project: "PLFSS 2022"
      - path: "exports_lectures/PLFSS 2022/lecture-an-15-4523-PO717460.json"
        default_processing_timestamp:
          year: 2021
          month: 7
          day: 1
        origin_project: "PLFSS 2022"
      - path: "exports_lectures/PLFSS 2023/lecture-senat-2022-2023-96-PO78718.json"
        default_processing_timestamp:
          year: 2022
          month: 7
          day: 1
        origin_project: "PLFSS 2023"
      - path: "exports_lectures/PLFSS 2023/lecture-an-16-274-PO791932.json"
        default_processing_timestamp:
          year: 2022
          month: 7
          day: 1
        origin_project: "PLFSS 2023"
      - path: "exports_lectures/PLFSS 2023/lecture-an-16-274-PO420120.json"
        default_processing_timestamp:
          year: 2022
          month: 7
          day: 1
        origin_project: "PLFSS 2023"
      - path: "exports_lectures/PLFSS 2023/lecture-an-16-1682-PO791932 (2).json"
        default_processing_timestamp:
          year: 2022
          month: 7
          day: 1
        origin_project: "PLFSS 2023"
      - path: "exports_lectures/PLFSS 2023/lecture-an-16-480-PO791932.json"
        default_processing_timestamp:
          year: 2022
          month: 7
          day: 1
        origin_project: "PLFSS 2023"
      - path: "exports_lectures/Export PLFSS 2024/JSON/lecture-an-16-1682-PO420120.json"
        default_processing_timestamp:
          year: 2023
          month: 7
          day: 1
        origin_project: "PLFSS 2024"
      - path: "exports_lectures/Export PLFSS 2024/JSON/lecture-an-16-1875-PO791932.json"
        default_processing_timestamp:
          year: 2023
          month: 7
          day: 2
        origin_project: "PLFSS 2024"
      - path: "exports_lectures/Export PLFSS 2024/JSON/lecture-senat-2023-2024-77-PO78718.json"
        default_processing_timestamp:
          year: 2023
          month: 7
          day: 3
        origin_project: "PLFSS 2025"
    excel_configs:
      - path: "exports_lectures/PLFSS 2025/BDD_AN_L1_SP_Amendements_copie_valeurs.xlsx"
        default_processing_timestamp:
          year: 2024
          month: 10
          day: 17
        origin_project: "PLFSS 2025"
      - path: "exports_lectures/PLFSS 2025/BDD_PLFSS_2025_SENAT_L1_SP.xlsx"
        default_processing_timestamp:
          year: 2024
          month: 11
          day: 20
        origin_project: "PLFSS 2025"

  PLACSS_2022:
    json_configs:
      - path: "exports_lectures/PLACSS 21/AN Séance 1ère lecture/lecture-an-16-1268-PO791932.json"
        default_processing_timestamp:
          year: 2022
          month: 7
          day: 1
        origin_project: "PLACSS 2021"
      - path: "exports_lectures/PLACSS 21/Sénat Séance 1ère lecture/lecture-senat-2022-2023-705-PO78718.json"
        default_processing_timestamp:
          year: 2022
          month: 7
          day: 1
        origin_project: "PLACSS 2021"
    excel_configs: []
  PLACSS_2024:
    json_configs:
      - path: "exports_lectures/PLACSS 21/AN Séance 1ère lecture/lecture-an-16-1268-PO791932.json"
        default_processing_timestamp:
          year: 2022
          month: 10
          day: 10
        origin_project: "PLACSS 2021"
      - path: "exports_lectures/PLACSS 21/Sénat Séance 1ère lecture/lecture-senat-2022-2023-705-PO78718.json"
        default_processing_timestamp:
          year: 2022
          month: 10
          day: 20
        origin_project: "PLACSS 2021"
      - path: "exports_lectures/PLACSS 2022/AN Commission/lecture-an-17-4-PO420120.json"
        default_processing_timestamp:
          year: 2023
          month: 10
          day: 10
        origin_project: "PLACSS 2022"
      - path: "exports_lectures/PLACSS 2023/lecture-an-17-4-PO838901.json"
        default_processing_timestamp:
          year: 2024
          month: 10
          day: 14
        origin_project: "PLACSS 2023"
      - path: "exports_lectures/PLACSS 2023/lecture-senat-2024-2025-35-PO78718.json"
        default_processing_timestamp:
          year: 2024
          month: 10
          day: 22
        origin_project: "PLACSS 2023"
      - path: "exports_lectures/PLACSS 2024/PLACSS2024_L1_AN_SP.json"
        default_processing_timestamp:
          year: 2025
          month: 6
          day: 10
        origin_project: "PLACSS 2024"

    excel_configs: []

  LFRSS:
    json_configs:
      - path: "exports_lectures/LFRSS 2023/lecture-an-16-760-PO791932.json"
        default_processing_timestamp:
          year: 2023
          month: 7
          day: 1
        origin_project: "LFRSS 2023"
      - path: "exports_lectures/LFRSS 2023/lecture-an-16-760-PO420120.json"
        default_processing_timestamp:
          year: 2023
          month: 7
          day: 1
        origin_project: "LFRSS 2023"
      - path: "exports_lectures/LFRSS 2023/lecture-senat-2022-2023-368-PO78718.json"
        default_processing_timestamp:
          year: 2023
          month: 7
          day: 1
        origin_project: "LFRSS 2023"
    excel_configs: []

  PPL_FIN_DE_VIE_2024:
    json_configs:
      - path: "exports_lectures/PPL LIOT 2023 abrogation réforme des retraites/Séance AN/lecture-an-16-1299-PO791932.json"
        default_processing_timestamp:
          year: 2023
          month: 7
          day: 1
        origin_project: "PPL LIOT abrogation réforme des retraites"
    excel_configs:
      - path: "exports_lectures/PPL Retraites/2024/PPL_retraites_RN_BDD.xlsx"
        default_processing_timestamp:
          year: 2024
          month: 10
          day: 1
        origin_project: "PPL Retraites 2024"
      - path: "exports_lectures/PPL fin de vie 2024/BDD_Commission_PJL fin de vie.xlsx"
        default_processing_timestamp:
          year: 2024
          month: 5
          day: 18
        origin_project: "PPL Fin de vie 2024"
      - path: "exports_lectures/PPL fin de vie 2024/BDD_Séance publique_PJL fin de vie.xlsx"
        default_processing_timestamp:
          year: 2024
          month: 5
          day: 19
        origin_project: "PPL Fin de vie 2024"

  PPL_FIN_DE_VIE_2025:
    json_configs: []
    excel_configs:
      - path: "exports_lectures/PPL fin de vie 2025/BDD_Fin_de_vie_CAS_04_2025.xlsx"
        default_processing_timestamp:
          year: 2025
          month: 4
          day: 1
        origin_project: "PPL Fin de vie 2025"
      - path: "exports_lectures/PPL fin de vie 2025/BDD_SPA_CAS_04_2025.xlsx"
        default_processing_timestamp:
          year: 2025
          month: 4
          day: 1
        origin_project: "PPL Fin de vie 2025"

  PLF:
    json_configs: []
    excel_configs:
      - path: "exports_lectures/PLF 2024/BDD_PLF_2024_SEN_L1_SP.xlsx"
        default_processing_timestamp:
          year: 2023
          month: 10
          day: 1
        origin_project: "PLF 2024"
      - path: "exports_lectures/PLF 2025/BDD_PLF_2025_AN_L1_COM_Affaires_sociales.xlsx"
        default_processing_timestamp:
          year: 2024
          month: 10
          day: 1
        origin_project: "PLF 2025"
      - path: "exports_lectures/PLF 2025/BDD_PLF_2025_AN_L1_COM_Finances.xlsx"
        default_processing_timestamp:
          year: 2024
          month: 11
          day: 1
        origin_project: "PLF 2025"
      - path: "exports_lectures/PLF 2025/BDD_PLF_2025_AN_L1_SP.xlsx"
        default_processing_timestamp:
          year: 2024
          month: 12
          day: 1
        origin_project: "PLF 2025"
