{{- if .Values.app.enabled }}
{{ include "graal.deployment" (dict "root" . "resource" .Values.app) }}
{{- end }}
{{- if and .Values.app.enabled .Values.api.enabled }}
---
{{- end }}
{{- if .Values.api.enabled }}
{{ include "graal.deployment" (dict "root" . "resource" .Values.api) }}
{{- end }}
