app:
  ~chart: app
  imagePackage: frontend
  probesPath: /live
  containerPort: 8080

api:
  ~chart: app
  imagePackage: api
  probesPath: /api/v1/health
  containerPort: 8000
  envFrom:
    - configMapRef:
        name: graal
  env:
    - name: FRONTEND_URL
      value: "https://{{ .Values.global.host }}"
