app:
  ~chart: app
  imagePackage: frontend
  probesPath: /live
  containerPort: 8080

api:
  ~chart: app
  imagePackage: api
  probesPath: /api/v1/health
  containerPort: 8000

pg:
  ~chart: pg

jobs:
  migrate:
    ~chart: job
    annotations:
      "kontinuous.dev/hook": "pre-deploy"
    imagePackage: api
    args:
      - bash
      - -c
      - alembic upgrade head
    envFrom:
      - configMapRef:
          name: graal
      - secretRef:
          name: pg-app
